<div class="container-fluid container-md">
    <div class="row">
        <div class="col ">
            <h1>Detail Pojištěnce</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-8 ">
            <table class="table table-hover table-borderless">
                <tr>
                    <td><?= htmlspecialchars($pojistenec['jmeno'])." ". htmlspecialchars($pojistenec['prijmeni'])?></td>
                    <td><?= htmlspecialchars($adresa['ulice'])." ". htmlspecialchars($adresa['cislo_popisne'])?></td>
                </tr>
                <tr>
                    <td><?= htmlspecialchars($pojistenec['email'])?></td>
                    <td><?= htmlspecialchars($adresa['mesto'])?></td>
                </tr>
                <tr>
                <td><?= htmlspecialchars($pojistenec['telefon'])?></td>
                <td><?= htmlspecialchars($adresa['PSC'])?></td>
                </tr>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col ">
            <h2>Sjednaná pojištění</h2>
        </div>
    </div>
    <div class="row my-4">
        <?php if(count($pojisteni) > 0) : ?>
            <div class="col text-center ">
                <table class="table table-hover">
                  <thead class="table-dark">
                        <tr>
                            <th scope="col">Pojištění</th>
                            <th scope="col">Pojistné</th>
                            <th scope="col"></th>
                        </tr>
                   </thead>                    
                    <tbody>
                        <?php foreach ($pojisteni as $jednoPojisteni) : ?>
                            <tr>
                                <td><?= htmlspecialchars($jednoPojisteni['typ']) ?></td>
                                <td><?= htmlspecialchars($jednoPojisteni['pojistne'].' Kč') ?></td>
                                <td><a href="detail-pojistence/<?= htmlspecialchars($pojistenec['klient_id']) ?>/odstran/<?= htmlspecialchars($jednoPojisteni['pojisteni_id']) ?>" 
                                class="btn btn-outline-danger mx-2" >Odstranit</a>
                                <a href="editace-pojisteni/<?= htmlspecialchars($pojistenec['klient_id']) ?>/<?= htmlspecialchars($jednoPojisteni['pojisteni_id']) ?>" 
                                class="btn btn-outline-warning mx-2" >Editovat</a></td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>        
            </div>
        <?php else : ?>
            <div calss="col">
                <?= htmlspecialchars($pojistenec['jmeno'])." ". htmlspecialchars($pojistenec['prijmeni']." nemá sjednané pojištění")?>
            </div>
        <?php endif; ?>
    </div>
    <div class="row">
        <div class="col text-center">
            <a href="editace-pojisteni/<?= htmlspecialchars($pojistenec['klient_id']) ?>" class="btn btn-primary mx-2" >Přidat pojištění</a>
            <a href="editace-pojistence/<?= htmlspecialchars($pojistenec['klient_id']) ?>" class="btn btn-warning mx-2 text-white" >Editovat</a>
            <a href="pojistenci/odstran/<?= htmlspecialchars($pojistenec['klient_id']) ?>" class="btn btn-danger mx-2" >Odstranit</a>
        </div>
    </div>
</div>