<div class="container-fluid container-md">
    <div class="row">
        <div class="col text-center">
            <h1>Seznam pojištěnců</h1>
        </div>
    </div>
    <div class="row my-4">
        <div class="col text-center">
            <a href="editace-pojistence" class="btn .btn-large btn-primary">Přidat pojištěnce</a>
        </div>
    </div>
    <div class="row my-4">
        <div class="col text-center ">
            <table class="table table-hover">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">Jméno</th>
                        <th scope="col">Bydliště</th>
                        <th scope="col">Telefon</th>
                        <th scope="col">Email</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>            
                    <?php foreach ($pojistenci as $pojistenec) : ?>
                        <?php if ($prihlasenyUzivatel['admin'] === 1) : ?>
                        <tr>
                            <td><a href="detail-pojistence/<?= htmlspecialchars($pojistenec['klient_id']) ?>">
                                <?= htmlspecialchars($pojistenec['jmeno']) ?></a></td>
                            <td><?= htmlspecialchars($pojistenec['adresa']) ?></td>
                            <td><?= htmlspecialchars($pojistenec['telefon']) ?></td>
                            <td><?= htmlspecialchars($pojistenec['email']) ?></td>
                            <td><a href="pojistenci/odstran/<?= htmlspecialchars($pojistenec['klient_id']) ?>" class="btn btn-outline-danger mx-2" >Odstranit</a>
                            <a href="editace-pojistence/<?= htmlspecialchars($pojistenec['klient_id']) ?>" class="btn btn-outline-warning mx-2" >Editovat</a></td>
                        </tr>
                        <?php elseif ($pojistenec['uzivatel'] == $prihlasenyUzivatel['uzivatel_id']) : ?>
                            <tr>
                            <td><a href="detail-pojistence/<?= htmlspecialchars($pojistenec['klient_id']) ?>">
                                <?= htmlspecialchars($pojistenec['jmeno']) ?></a></td>
                            <td><?= htmlspecialchars($pojistenec['adresa']) ?></td>
                            <td><?= htmlspecialchars($pojistenec['telefon']) ?></td>
                            <td><?= htmlspecialchars($pojistenec['email']) ?></td>
                            <td><a href="pojistenci/odstran/<?= htmlspecialchars($pojistenec['klient_id']) ?>" class="btn btn-outline-danger mx-2" >Odstranit</a>
                            <a href="editace-pojistence/<?= htmlspecialchars($pojistenec['klient_id']) ?>" class="btn btn-outline-warning mx-2" >Editovat</a></td>
                        </tr>
                        <?php endif; ?>    
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <?= $strankovani[0]->paginace('pojistenci', $strankovani[1], $strankovani[2], '?strana={strana}') ?>
        </div>
    </div>
</div>



