<div class="container-fluid container-md">
    <div class="row">
        <div class="col">
        <h1>Přidat uživatele</h1>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-4">
            <form method="post">
                <div class="mb-2">
                    <label for="vstupJmeno" class="form-label">Jméno</label>
                    <input type="text" class="form-control" id="vstupJmeno" name="jmeno" placeholder="Přihlašovací jméno">
                </div>
                <div class="mb-2">
                    <label for="vstupHeslo" class="form-label">Heslo</label>
                    <input type="password" class="form-control" name="heslo" id="vstupHeslo" placeholder="Zadejte heslo">
                </div>
                <div class="mb-2">
                    <label for="vstupHesloZnovu" class="form-label">Heslo znovu</label>
                    <input type="password" class="form-control" name="heslo_znovu" id="vstupHesloZnovu" placeholder="Zadejte heslo pro ověření">
                </div>
                <button type="submit" class="btn btn-primary">Registrovat</button>
            </form>
        </div>
    </div>
</div>

