<div class="container-fluid container-md">
    <div class="row">
        <div class="col">
        <h3>Zadejte prosím vaše přihlasovací údaje</h3>
        </div>
    </div>
    <div class="row mb-5">
        <div class="col-4">
            <form method="post">
                <div class="mb-2">
                    <label for="vstupJmeno" class="form-label">Jméno</label>
                    <input type="text" class="form-control" id="vstupJmeno" name="jmeno" placeholder="Přihlašovací jméno">
                </div>
                <div class="mb-2">
                    <label for="vstupHeslo" class="form-label">Heslo</label>
                    <input type="password" class="form-control" name="heslo" id="vstupHeslo" placeholder="Zadejte heslo">
                </div>
                <button type="submit" class="btn btn-primary">Přihlásit se</button>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col">
        <p>Pokud zatím nemáte účet, kontatkujte prosím administrátora</p>
        </div>
    </div>
</div>


