<!DOCTYPE html>
<html lang="cs-cz">
    <head>
        <base href="/localhost" />
        <meta charset="UTF-8" />
        <title><?= $titulek ?></title>
        <meta name="description" content="<?= $popis ?>" />
        <meta name="keywords" content="<?= $klicova_slova ?>" />
        <link rel="stylesheet" href="bootstrap.css" type="text/css"/>
        <script src="bootstrap.bundle.js" type="text/javascript"></script>
    </head>

    <body>
        <nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light mb-5">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="obrazky/logo.png" alt="" width="40" height="40" class="d-inline-block align-text-top">
                Vaše Pojišťovna
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#obsah-navigacni-listy" aria-controls="obsah-navigacni-listy" aria-expanded="false" aria-label="Rozbalit navigaci">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="obsah-navigacni-listy">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item active">
                        <a class="nav-link" href="pojistenci">Pojištěnci</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="pojisteni">Pojištění</a>
                    </li>
                    <?php if($prihlasenyUzivatel && ($prihlasenyUzivatel['admin'] == 1)) : ?>
                        <li><a class="nav-link" href="uzivatele">Uživatelé</a></li>
                    <?php endif; ?>
                </ul>
                <?php if(!$prihlasenyUzivatel) : ?>
                    <a href="prihlaseni" class="btn btn-outline-primary" >Přihlásit se</a>
                <?php else : ?>
                    <?php if($prihlasenyUzivatel['admin'] == 1) : ?>
                        <a href="pridej-uzivatele" class="btn btn-outline-success mx-2" >Přidat uživatele</a>
                    <?php endif; ?>
                    <a href="prihlaseni/odhlasit" class="btn btn-outline-dark" >Odhlásit se</a>
                <?php endif; ?>
                </div>
            </div>
        </nav>
        <?php foreach ($zpravy as $zprava) : ?>
            <p class="zprava"><?= $zprava ?></p>
        <?php endforeach ?>
        <article>
        <?php $this->kontroler->vypisPohled(); ?>
        </article>
    </body>
</html>