<div class="container-fluid container-md">
  <div class="row">
    <div class="col text-center">
        <h1>Výběr uživatelů</h1>
    </div>
    </div>
    <div class="row">
    <div class="col text-center">
        <a href="pridej-uzivatele" class="btn btn-primary mt-2" >Přidat uživatele</a>
    </div>
    </div>
    <div class="row my-4">
        <div class="col text-center ">
            <table class="table table-hover">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">Jméno uživatele</th>
                        <th scope="col">Admin</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>                
                    <?php foreach ($uzivatele as $uzivatel) : ?>
                        <tr>
                            <td><?= htmlspecialchars($uzivatel['jmeno']) ?></td>
                            <td><?php if ($uzivatel['admin'] == 1) : ?>
                                Ano
                                <?php else : ?>
                                Ne
                                <?php endif; ?>                    
                            </td>
                            <td><a href="uzivatele/odstran/<?= htmlspecialchars($uzivatel['uzivatel_id']) ?>" class="btn btn-outline-danger mx-2" >Odstranit</a>
                            <a href="editace-uzivatele/<?= htmlspecialchars($uzivatel['uzivatel_id']) ?>" class="btn btn-outline-warning mx-2" >Editovat</a></td>
                        </tr> 
                    <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <?= $strankovani[0]->paginace('uzivatele', $strankovani[1], $strankovani[2], '?strana={strana}') ?>
        </div>
    </div>
</div>



